-- 023_fix_zero_scores.sql
-- Remove signals that have zero or null evidence scores.
-- Rationale: all pipelines now filter out 0-score signals before insertion.
-- Any 0-score rows that remain are legacy records from before the scoring
-- framework was in place. They lack the per-dimension scores needed to
-- display correctly on the frontend and should be regenerated by the pipelines.
-- Generated: 2026-04-15

-- Step 1: Delete sources attached to zero-score signals
DELETE FROM sources
WHERE signal_id IN (
  SELECT id FROM repurposing_signals
  WHERE total_evidence_score = 0
     OR total_evidence_score IS NULL
);

-- Step 2: Delete the zero-score signals themselves
DELETE FROM repurposing_signals
WHERE total_evidence_score = 0
   OR total_evidence_score IS NULL;

-- Verification: should return 0 rows
-- SELECT COUNT(*) FROM repurposing_signals
-- WHERE total_evidence_score = 0 OR total_evidence_score IS NULL;
